import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import { ToggleContextProvider } from '@/context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Vikas Thakur',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {' '}
        <ToggleContextProvider>
          <div className="flex">
            <Sidebar />
            <main className="flex-1 sm:ml-56 ">{children}</main>
          </div>
        </ToggleContextProvider>
      </body>
    </html>
  );
}
